### ISSUE TITLE
Create toy sample data for testing

### ISSUE THREAD

**Issue by WeilinHan8** [UBC-MDS/Group_9_GA_Metrics#1]
Hi Beth,

Could you please add toy sample GA data for testing thank you!

**Comment by beth-ouyang** [comment]
Uploaded~~ And pull requested is also created!

**Comment by WeilinHan8** [comment]
Change this issue to milestone 2 since it's part of work of writing test.

**Comment by WeilinHan8** [comment]
Here are the columns name you might need:
[date]: 20220801 to 20220825, 
[fullVisitorId], 
[totals.visits], 
[totals.transactions (1 or blank)], 
[totals.transactionRevenue],
[totals.newVisits],
[trafficSource.adwordsClickInfo.campaignId]: 219011657, 140569061, 215934049, 123851219

**Comment by WeilinHan8** [comment]
PR #31
