### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by WeilinHan8** [UBC-MDS/Group_9_GA_Metrics#4]
Hi Ian,

Could you please update README.md.
Here is instruction from Tiff:
a summary paragraph that describes the project at a high level
a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)
a paragraph describing where your packages fit into the Python ecosystem (are there any other Python packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).

Please give update below.

Thank you.

**Comment by ianm99** [comment]
I added a piece to the readme about how our package fits into the python ecosystem. it's in this pull request [https://github.com/UBC-MDS/Group_9_GA_Metrics/pull/14](url)

**Comment by WeilinHan8** [comment]
Thanks Ian, I made further changes in #15  & #23
